### ISSUE TITLE
Header information on readthedocs page

### ISSUE THREAD

**Issue by ChrisJarka** [WycliffeAssociates/btt-writer-docs#1]
@PurpleGuitar You did such a great job on fixing this on the BTT Recorder site - please do it again only for this site. 

![Snag_f819c17](https://user-images.githubusercontent.com/9850185/68038696-ecd72380-fca0-11e9-8dd4-cbce44ca0424.png)

**Comment by PurpleGuitar** [comment]
Changed.  Please review and make sure I got it right this time.  :)

**Comment by ChrisJarka** [comment]
Thank you!
